web:
  build: .
  volumes:
    - .:/myapp
  links:
    - db
    - redis
  ports:
    - "3000:3000"
  command: bundle exec rails server -b 0.0.0.0
worker:
  build: .
  volumes:
    - .:/myapp
  links:
    - db
    - redis
  command: bundle exec sidekiq
db:
  image: postgres
redis:
  image: redis
cache:
  image: koudaiii/varnish-sample
  environment:
    - "VARNISH_BACKEND_PORT=3000"
    - "VARNISH_PORT=8080"
    - "VARNISH_BACKEND_IP=web"
  ports:
    - "8080:80"
  links:
    - web
