web:
  build: .
  links:
    - db
    - redis
  ports:
    - "8080"
  command: sh script/server
worker:
  build: .
  links:
    - db
    - redis
  command: bundle exec sidekiq
db:
  image: postgres
redis:
  image: redis
cache:
  image: koudaiii/varnish-sample
  environment:
    - "VARNISH_BACKEND_PORT=3000"
    - "VARNISH_PORT=8080"
    - "VARNISH_BACKEND_IP=web"
  ports:
    - "8080:80"
  links:
    - web
