web:
  build: .
  ports:
    - "8080"
  command: sh script/server
  links:
      - db
      - redis
worker:
  build: .
  command: bundle exec sidekiq
  links:
      - db
      - redis
db:
  image: postgres
redis:
  image: redis
