web:
  build: .
  links:
    - db
    - redis
  ports:
    - "8080"
  command: sh script/server
worker:
  build: .
  links:
    - db
    - redis
  command: bundle exec sidekiq
db:
  image: postgres
redis:
  image: redis
