web:
  build: .
  ports:
    - "8080"
  command: sh script/server
  links:
      - db
      - redis
worker:
  build: .
  command: sh script/worker
  links:
      - db
      - redis
db:
  image: postgres
  environment:
      - "affinity:com.docker.compose.service==web"
      - "affinity:com.docker.compose.service==worker"
redis:
  image: redis
  environment:
      - "affinity:com.docker.compose.service==web"
      - "affinity:com.docker.compose.service==worker"
